-- USERS
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR2(60) NOT NULL,
  last_name VARCHAR2(60) NOT NULL,
  email VARCHAR2(190) UNIQUE NOT NULL,
  password VARCHAR2(255) NOT NULL,
  role VARCHAR2(20) DEFAULT 'customer' CHECK (role IN ('customer','admin')),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CATEGORIES
CREATE TABLE categories (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- PRODUCTS
CREATE TABLE products (
  id VARCHAR2(20) PRIMARY KEY,
  name VARCHAR2(255) NOT NULL,
  description VARCHAR2(500),
  price NUMBER(10,2) NOT NULL,
  image VARCHAR2(500),
  calories NUMBER,
  sale_type VARCHAR2(20) DEFAULT 'fixed' CHECK (sale_type IN ('fixed','variable')),
  unit VARCHAR2(50) DEFAULT 'items',
  unit_weight NUMBER,
  recommended NUMBER(1) DEFAULT 0,
  tags CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_recommended ON products(recommended);

-- PRODUCT CATEGORIES
CREATE TABLE product_categories (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id VARCHAR2(20) NOT NULL,
  category_id NUMBER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pc_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT fk_pc_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
  CONSTRAINT unique_product_category UNIQUE (product_id, category_id)
);

-- ADDRESSES
CREATE TABLE addresses (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  label VARCHAR2(100),
  street_address VARCHAR2(255) NOT NULL,
  city VARCHAR2(100) NOT NULL,
  province VARCHAR2(100),
  postal_code VARCHAR2(20),
  phone_number VARCHAR2(30),
  delivery_instructions VARCHAR2(500),
  country VARCHAR2(100) DEFAULT 'Pakistan',
  latitude NUMBER(10,8),
  longitude NUMBER(11,8),
  is_default NUMBER(1) DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_addr_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_user_id ON addresses(user_id);

-- CART ITEMS
CREATE TABLE cart_items (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  product_id VARCHAR2(20) NOT NULL,
  quantity NUMBER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT unique_user_product UNIQUE (user_id, product_id)
);

-- ORDERS
CREATE TABLE orders (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  order_number VARCHAR2(24) UNIQUE NOT NULL,
  status VARCHAR2(20) DEFAULT 'placed' CHECK (status IN ('placed','in-transit','delivered','cancelled')),
  subtotal NUMBER(10,2) NOT NULL,
  shipping NUMBER(10,2) NOT NULL,
  taxes NUMBER(10,2) NOT NULL,
  total NUMBER(10,2) NOT NULL,
  payment_method VARCHAR2(40),
  delivery_notes VARCHAR2(500),
  address_snapshot CLOB,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_orders_user_created ON orders(user_id, created_at);

-- ORDER ITEMS
CREATE TABLE order_items (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id NUMBER NOT NULL,
  product_id VARCHAR2(20) NOT NULL,
  product_name VARCHAR2(255) NOT NULL,
  quantity NUMBER NOT NULL,
  unit_price NUMBER(10,2) NOT NULL,
  line_total NUMBER(10,2) NOT NULL,
  sale_type VARCHAR2(20) DEFAULT 'fixed',
  unit VARCHAR2(50) DEFAULT 'items',
  unit_weight NUMBER,
  image VARCHAR2(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE INDEX idx_order_items_order_id ON order_items(order_id);

